### ISSUE TITLE
Alt data stream and skipping sparse clusters

### ISSUE THREAD

**Issue by marcurdy** [jschicht/RawCopy#9]
Does this support alternate data streams and skipping sparse clusters as seen in USN journals?

Thanks.

**Comment by jschicht** [comment]
No. RawCopy is simply copying the "normal" data of a file (the first unamed stream) as is. That is the initialized size, including any sparse clusters. If you are after a tool to copy all attributes, you can look into https://github.com/jschicht/ExtractAllAttributes . If you are specifically after the Usn journal you can look into  https://github.com/jschicht/ExtractUsnJrnl which is skipping all the irrelevant sparse clusters in that otherwise huge file, and targets the relevant named stream.

**Comment by marcurdy** [comment]
Thanks a-plenty

**Comment by jschicht** [comment]
Btw, I forgot you could also use the /AllAttr:1 param with RawCopy.
